//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIS752CardGame.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public game()
        {
            this.player_game = new HashSet<player_game>();
        }
    
        public string game_id { get; set; }
        public string table_id { get; set; }
        public bool completed { get; set; }
        public string game_info { get; set; }
    
        public virtual ICollection<player_game> player_game { get; set; }
    }
}
