//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIS752CardGame.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_game
    {
        public string user_id { get; set; }
        public string game_id { get; set; }
        public Nullable<int> ante_bet { get; set; }
        public Nullable<int> amt_won_lost { get; set; }
        public string player_hand { get; set; }
        public bool has_anted_bet { get; set; }
        public string player_actions { get; set; }
    
        public virtual game game { get; set; }
        public virtual user user { get; set; }
    }
}
