//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIS752CardGame.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class poker_table
    {
        public poker_table()
        {
            this.users = new HashSet<user>();
        }
    
        public string table_id { get; set; }
        public int table_game_type { get; set; }
        public string table_disp_name { get; set; }
        public Nullable<int> ante { get; set; }
        public Nullable<int> max_raise { get; set; }
        public int max_players { get; set; }
        public string table_deck { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
