//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIS752CardGame.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public game()
        {
            this.player_game = new HashSet<player_game>();
        }
    
        public string game_id { get; set; }
        public string table_id { get; set; }
        public int game_state { get; set; }
        public string house_cards { get; set; }
        public int table_pot_value { get; set; }
        public int current_round_bet { get; set; }
        public string req_player_action { get; set; }
        public string last_action { get; set; }
        public int last_raise_value { get; set; }
    
        public virtual ICollection<player_game> player_game { get; set; }
    }
}
