//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIS752CardGame.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_pwd_reset
    {
        public string user_id { get; set; }
        public string verification_code { get; set; }
        public bool is_valid { get; set; }
        public string sent_to { get; set; }
        public System.DateTime sent_date { get; set; }
        public System.DateTime validated_date { get; set; }
    
        public virtual user user { get; set; }
    }
}
